CRITICAL - 2025-07-24 12:43:29 --> ErrorException: Undefined variable $router
[Method: GET, Route: /]
in APPPATH/Config/Routes.php on line 9.
 1 APPPATH/Config/Routes.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $router', '/var/www/html/app/Config/Routes.php', 9)
 2 SYSTEMPATH/Router/RouteCollection.php(339): require('/var/www/html/app/Config/Routes.php')
 3 SYSTEMPATH/CodeIgniter.php(821): CodeIgniter\Router\RouteCollection->loadRoutes()
 4 SYSTEMPATH/CodeIgniter.php(455): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 5 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-07-24 12:45:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:45:30 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:45:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:45:37 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:49:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:49:17 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:49:30 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:49:30 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:56:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:56:14 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:56:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:56:25 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:57:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:57:15 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:58:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:58:14 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 12:58:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 12:58:32 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 13:00:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 13:00:15 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 13:00:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 13:00:42 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 13:01:18 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 13:01:18 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 13:03:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'app_user'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'%' to database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 13:03:13 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'%' to database 'sistema-inventario'
ERROR - 2025-07-24 13:05:14 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 13:05:14 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Unknown database 'sistema-inventario'
ERROR - 2025-07-24 13:05:31 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:201
Stack trace:
#0 /var/www/html/system/Database/MySQLi/Connection.php(201): mysqli->real_connect('db', 'app_user', Object(SensitiveParameterValue), 'sistema-inventa...', 3306, '', 0)
#1 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#4 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#5 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#6 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#7 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'sistema-inventario' in /var/www/html/system/Database/MySQLi/Connection.php:246
Stack trace:
#0 /var/www/html/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /var/www/html/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 /var/www/html/app/Controllers/Auth/AuthController.php(136): CodeIgniter\Database\BaseConnection->query('CALL buscarUsua...', Array)
#3 /var/www/html/app/Controllers/Auth/AuthController.php(27): App\Controllers\Auth\AuthController->buscarUsuarioPorNombre('Star')
#4 /var/www/html/system/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
#5 /var/www/html/system/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
#6 /var/www/html/system/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /var/www/html/system/Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 /var/www/html/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 /var/www/html/public/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 {main}
ERROR - 2025-07-24 13:05:31 --> Error al usar la función buscarUsuarioPorNombre en AuthControllerUnable to connect to the database.
Main connection [MySQLi]: Unknown database 'sistema-inventario'
CRITICAL - 2025-07-24 13:06:52 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/login]
in APPPATH/Helpers/jwt_helper.php on line 43.
 1 APPPATH/Controllers/Auth/AuthController.php(32): obtenerJWT(Object(stdClass))
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
 3 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
 4 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-07-24 13:08:02 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/login]
in APPPATH/Helpers/jwt_helper.php on line 43.
 1 APPPATH/Controllers/Auth/AuthController.php(32): obtenerJWT(Object(stdClass))
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
 3 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
 4 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-07-24 13:08:37 --> Error: Call to undefined function App\Controllers\Auth\obtenerJWT()
[Method: POST, Route: auth/login]
in APPPATH/Controllers/Auth/AuthController.php on line 32.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
 2 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
 3 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-07-24 13:10:13 --> Error: Call to undefined function App\Controllers\Auth\obtenerJWT()
[Method: POST, Route: auth/login]
in APPPATH/Controllers/Auth/AuthController.php on line 32.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
 2 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
 3 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-07-24 13:27:06 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/login]
in APPPATH/Helpers/jwt_helper.php on line 43.
 1 APPPATH/Controllers/Auth/AuthController.php(32): obtenerJWT(Object(stdClass))
 2 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Auth\AuthController->login()
 3 SYSTEMPATH/CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth\AuthController))
 4 SYSTEMPATH/CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH/Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
